# Generated by Django 5.1.3 on 2025-11-22 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.product'),
        ),
        migrations.AddField(
            model_name='supplierinfo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='supplierinfo',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.supplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(related_name='products', through='products.SupplierInfo', to='products.supplier'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['product', '-created_at'], name='products_in_product_06c00d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierinfo',
            unique_together={('supplier', 'product')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', 'sku'], name='products_pr_shop_id_598623_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', 'is_active'], name='products_pr_shop_id_44685a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('sku', 'shop')},
        ),
    ]
