# Generated by Django 5.1.3 on 2025-11-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='daily', max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_transactions', models.IntegerField(default=0)),
                ('average_transaction_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_items_sold', models.IntegerField(default=0)),
                ('cash_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('card_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mobile_money_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unique_customers', models.IntegerField(default=0)),
                ('new_customers', models.IntegerField(default=0)),
                ('returning_customers', models.IntegerField(default=0)),
                ('top_products', models.JSONField(default=list)),
                ('low_stock_items', models.IntegerField(default=0)),
                ('out_of_stock_items', models.IntegerField(default=0)),
                ('cashier_performance', models.JSONField(default=dict)),
                ('peak_hour', models.IntegerField(blank=True, null=True)),
                ('peak_day', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PredictiveMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('demand_forecast', 'Demand Forecast'), ('stock_recommendation', 'Stock Recommendation'), ('revenue_prediction', 'Revenue Prediction'), ('churn_risk', 'Churn Risk')], max_length=50)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('predicted_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('confidence_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('prediction_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-prediction_date'],
            },
        ),
    ]
