# Generated by Django 5.1.3 on 2025-11-22 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticssnapshot',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='predictivemetric',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop'),
        ),
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=models.Index(fields=['shop', 'date'], name='analytics_a_shop_id_faec3b_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=models.Index(fields=['date', 'period_type'], name='analytics_a_date_e272e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='analyticssnapshot',
            unique_together={('shop', 'date', 'period_type')},
        ),
        migrations.AddIndex(
            model_name='predictivemetric',
            index=models.Index(fields=['shop', 'metric_type', 'prediction_date'], name='analytics_p_shop_id_62a6ba_idx'),
        ),
    ]
