# Generated by Django 5.1.3 on 2025-11-22 18:59

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, help_text='Cash in drawer at shift start', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, help_text='Cash in drawer at shift end', max_digits=10, null=True)),
                ('expected_cash', models.DecimalField(decimal_places=2, default=0, help_text='Expected cash based on transactions', max_digits=10)),
                ('cash_difference', models.DecimalField(decimal_places=2, default=0, help_text='Difference between expected and actual', max_digits=10)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('card_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mobile_money_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transactions_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('suspended', 'Suspended')], default='open', max_length=20)),
                ('opening_notes', models.TextField(blank=True)),
                ('closing_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ShiftActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('clock_in', 'Clock In'), ('clock_out', 'Clock Out'), ('break_start', 'Break Start'), ('break_end', 'Break End'), ('cash_drop', 'Cash Drop'), ('cash_pickup', 'Cash Pickup'), ('note', 'Note')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Shift activities',
                'ordering': ['created_at'],
            },
        ),
    ]
