# Generated by Django 5.1.3 on 2025-11-22 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shifts', '0001_initial'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shift',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shift',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='shiftactivity',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='shifts.shift'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['cashier', 'status'], name='shifts_shif_cashier_a7910e_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['shop', 'start_time'], name='shifts_shif_shop_id_fc9a37_idx'),
        ),
    ]
